### ISSUE TITLE
sbshell启动singbox后，

### ISSUE THREAD

**Issue by userygy2001** [qichiyuhub/sbshell#3]
thubusercontent.com/qichiyuhub/rule/refs/heads/master/config/singbox/config_tproxy.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 37586  100 37586    0     0  12609      0  0:00:02  0:00:02 --:--:-- 12608
配置文件更新成功!
sing-box 启动成功
=========== Sbshell 管理菜单 ===========
1. Tproxy/Tun模式切换
2. 手动更新配置文件
3. 自动更新配置文件
4. 手动启动 sing-box
5. 手动停止 sing-box
6. 安装/更新 sing-box
7. 默认参数设置
8. 设置自启动
9. 网络设置(只支持debian)
10. 常用命令
11. 更新脚本
0. 退出
=======================================
请选择操作: 4
是否启动 sing-box?(y/n): y
检测是否处于非代理环境...
当前网络环境非代理网络，可以启动 sing-box。
应用 TProxy 模式下的防火墙规则...
清理 sing-box 相关的防火墙规则

Socket error Event: 32 Error: 10053.
Connection closing...Socket close.

Connection closed by foreign host.

Disconnected from remote host(新建会话) at 17:16:02.

Type `help' to learn how to use Xshell prompt.
[C:\~]$

**Comment by qichiyuhub** [comment]
描述清楚点  什么系统、什么环境下的系统、是否root登录，有没有更换ssh工具尝试

**Comment by userygy2001** [comment]
> 描述清楚点 什么系统、什么环境下的系统、是否root登录，有没有更换ssh工具尝试

阿里云的云服务器，系统是Ubuntu 22.04 64位，是root登录，更换ssh后也失败

**Comment by qichiyuhub** [comment]
云服务器部署的系统一般会有修改，并且网络环境权限等问题，本地使用吧。
